# This is my own workflow. Currently using this to learn how to create jobs.

name: MyOwnWorkflow

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: first
